### ISSUE TITLE
Corrupt parquet files will be created for some float data

### ISSUE THREAD

**Issue by matthros** [G-Research/ParquetSharp#166] opened 2021-02-12 19:00 UTC
I created a parquet file with different columns. 2 float data columns get corrupted (no longer possible to open them with apache drill or parquet.NET for example (index out of bound exception). If I change the data type to double in c#, the parquet file will be generated in the right way. I am writing the files exactly like documented under "Low-level API".

update: 99 % of generated parquet files are working, but some of them are failing (reproducible). Maybe some inconsistency in float32 handling in c# and c++?

[parquet_output.zip](https://github.com/G-Research/ParquetSharp/files/5974019/parquet_output.zip)

**Comment by matthros** [comment] 2021-02-12 19:04
@GPSnoopy , saw that your are very active in this repo, Can I send you the files (parquet file, exception etc.). My zip upload always fails.

**Comment by philjdf** [comment] 2021-02-12 19:09
Hi, do you have example code which reproduces this problem please?

**Comment by matthros** [comment] 2021-02-12 19:14
@philjdf , It is reproducible but cannot share the code (big company) but I can send you the output in parquet and csv format. If I read them with pandas and write it back to parquet with pyarrow engine (same as used in this repo) I got the same problem. If I write it back with "fastparquet" engine there is no problem. Further if I change the column data types from float32 to float64 in pandas  dataframe and write it back I will be fine too.

**Comment by philjdf** [comment] 2021-02-12 19:53
So your code can write a CSV, and if you read it using pandas and write it to parquet using pyarrow, you get a corrupted parquet file? You say 99% of the parquet files work - is the CSV fixed or are you using different input data each time you write a file?

Would mention that newer versions/features of Arrow may write parquet files not compatible with the versions of other libraries you've tried, but it's interesting that you say float64s don't have the problem.

**Comment by matthros** [comment] 2021-02-12 19:58
No, I create a parquet file using ParquetSharp. Those parquet files work in 99 % of the cases, but sometimes it gets corrupt (not possible to read them with apache drill or Parquet.Net. If I read the parquet files via pandas and export it again to parquet using pyarrow it changes nothing and the bug still appear. But if I export the pandas dataframe using fastparquet engine it is working. And if I change the pandas dataframe data types from float32 to float64 and then export it to parquet it is also working. It seems that arrow is not able the float data types generated by the ParquetSharp libary in some cases. Take a look on my added parquet file! Thx

**Comment by matthros** [comment] 2021-02-12 20:37
Think I have found the problem. It seems that arrows write float values "0" and it seems that many libaries are not able to handle that. Maybe because they expect something like "0.0" to detect them as float?

**Comment by GPSnoopy** [comment] 2021-02-13 00:28
> If I read the parquet files via pandas and export it again to parquet using pyarrow it changes nothing and the bug still appear.

That would imply that the bug is in Apache Arrow and not ParquetSharp, since both pyarrow and ParquetSharp are implemented using Apache Arrow.

- Which version of pyarrow have you tried? Version 3.0.0 should be the latest.
- Is the bug 100% reproducible if you use the same data and column schema?
- If so I would suggest you do a minimal reproducible example and submit it to https://issues.apache.org/jira/projects/ARROW.

Also give the latest checkout of ParquetSharp a go (https://github.com/G-Research/ParquetSharp/tree/75cbcd7b06c375b6329a6d0a6bb2ff6cfc0b8505), as it's been recently upgraded to Arrow 3.0.0 and they do fix quite a lot of problem in every new release.

**Comment by matthros** [comment] 2021-02-15 11:41
@GPSnoopy, I tried it with different versions of pyarrow, the problem remains the same and is always reproducible. I tried it with pyarrow 3.0.0 too, so I have not much hope that an upgrade will help.

**Comment by GPSnoopy** [comment] 2021-02-15 12:08
Suggest that at the very least you try isolating to a reproducible example in ParquetSharp (in code), or better directly in Arrow C++.

Can you narrow down the data that's causing the problem?
Do you have multiple row-groups? Can you reduce the number of row groups?
Can you remove columns and still reproduce the problem?
Can you remove some rows?
Etc...

**Comment by matthros** [comment] 2021-02-15 12:32
https://issues.apache.org/jira/browse/ARROW-11629
Posted it to apache ticket system. I have single row group. And the bug only occur in 2 of the float32 columns.
If I remove them or cast them to float64 the problem disappear.

**Comment by GPSnoopy** [comment] 2021-02-15 14:28
Interestingly, if you can round-trip the file in Arrow/Parquet, they might likely tell you the problem is with Parquet .NET or Apache Drill not correctly reading the file.

**Comment by matthros** [comment] 2021-02-15 14:44
But my files are working in 99 % of the cases. There must be something which is different in those parquet/csv file I attached. Maybe c# manages float32 different than the underlying c++ arrow api. I don't think that it is a random that 2 of my existing tools are not able to read the file. Further, if I read the csv file and write it down again with fastparquet engine, everything is working fine.

**Comment by GPSnoopy** [comment] 2021-02-15 14:48
`Parquet .NET` != `Arrow Parquet` != `fastparquet`

While each implementation is based on `Parquet.Format`, they don't necessarily support the same features and encoding. Also there are bugs in each implementation as well. Don't assume that, if library A can read the file but library B cannot, A or B are the culprit.

In this case, either Arrow is generating an incorrect file (but can still somehow read it back), or the file is correct and the problems lies with the other libraries.

**Comment by matthros** [comment] 2021-02-16 10:45
Yes, and I want to find the differences. I always write our measurement parquet files with parquetSharp. In 99 % the parquet files can be read from all other libaries, but sometimes not. The parquet files always have the same structure, so I am not able to detect what breaks it for other libaries.

**Comment by GPSnoopy** [comment] 2021-02-16 15:38
@matthros Humour me, could you make sure you've disabled dictionary encoding for the float column?

We've found an issue with Parquet .NET when serialising a large number of float values using dictionary encoding (see https://github.com/aloneguid/parquet-dotnet/issues/81). I wonder if it could be a similar problem.

In general, we do not recommend using dictionary encoding (on by default) for float values that do not have a lot of repetition.

**Comment by matthros** [comment] 2021-02-17 15:26
@GPSnoopy, what do you mean with "dictionary encoding"? As I wrote, Parquet.Net is not the only tool/library which has troubles reading the file.

**Comment by GPSnoopy** [comment] 2021-02-17 16:09
I've commented in more detail here:
https://issues.apache.org/jira/browse/ARROW-11629?focusedCommentId=17285936&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17285936

**Comment by matthros** [comment] 2021-02-17 16:37
I have check it and if I disable directory encoding in pyarrow it works with apache drill and parquet.net. Now the question is if it is a bug in arrow/parquet c++ or in parquet-dotnet/drill

**Comment by GPSnoopy** [comment] 2021-04-07 23:08
Confirmed to be fixed in latest versions of Parquet.Net & co.

**Closed by GPSnoopy** 2021-04-07 23:08 UTC
